#!/bin/bash
# Quick Deployment Script for SRPSS Website

echo "🚀 SRPSS School Website - Quick Deployment"
echo "==========================================="
echo ""
echo "📋 Checking Git Status..."
git status
echo ""
echo "✅ Git is ready to push!"
echo ""
echo "📝 DEPLOYMENT OPTIONS:"
echo ""
echo "1️⃣  Option A: GitHub CLI"
echo "   gh auth login"
echo "   cd d:\\sujeet\\school"
echo "   git push -u origin main"
echo ""
echo "2️⃣  Option B: Personal Access Token"
echo "   - Generate token at: github.com/settings/personal-access-tokens"
echo "   - git config --global credential.helper store"
echo "   - git remote set-url origin https://TOKEN@github.com/sujeet0139/sprrs.git"
echo "   - git push -u origin main"
echo ""
echo "3️⃣  Option C: SSH Keys"
echo "   - ssh-keygen -t rsa -b 4096"
echo "   - Add key to: github.com/settings/keys"
echo "   - git push -u origin main"
echo ""
echo "📌 After pushing to GitHub:"
echo "   1. Go to https://vercel.com/new"
echo "   2. Select sprrs repository"
echo "   3. Click Deploy"
echo "   4. Website live in 1-2 minutes!"
echo ""
echo "🎉 Your website will be live at: https://sprrs.vercel.app"
